# render.yaml
services:
  # Serviço da API Flask
  - type: web
    name: obesity-api
    env: docker
    repo: https://github.com/luishrufino/obesity-predict-model
    plan: free
    dockerBuild:
      context: ./api
      dockerfile: ./api/Dockerfile

  # Serviço do App Streamlit
  - type: web
    name: obesity-streamlit-app
    env: docker
    repo: https://github.com/luishrufino/obesity-predict-model
    plan: free
    dockerBuild:
      context: ./streamlit
      dockerfile: ./streamlit/Dockerfile
    envVars:
      - key: API_URL
        value: http://obesity-api:10000